// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzRuV3LjiuFfFtDta4qYB-mJ5FEpywW9s',
    appId: '1:2460746938:web:1135bb76023c67b0352e83',
    messagingSenderId: '2460746938',
    projectId: 'cv-project290m',
    authDomain: 'cv-project290m.firebaseapp.com',
    storageBucket: 'cv-project290m.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhOd0kQ5UaAai6bBvQvEIdUi3JAFsDS1I',
    appId: '1:2460746938:android:5e63736c5282fbe2352e83',
    messagingSenderId: '2460746938',
    projectId: 'cv-project290m',
    storageBucket: 'cv-project290m.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbLIYWWFLpECvQcBWi-WHWIr-aT959YcY',
    appId: '1:2460746938:ios:f6577ce39ad40c81352e83',
    messagingSenderId: '2460746938',
    projectId: 'cv-project290m',
    storageBucket: 'cv-project290m.firebasestorage.app',
    iosBundleId: 'cvproject.almomani.cvProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbLIYWWFLpECvQcBWi-WHWIr-aT959YcY',
    appId: '1:2460746938:ios:f6577ce39ad40c81352e83',
    messagingSenderId: '2460746938',
    projectId: 'cv-project290m',
    storageBucket: 'cv-project290m.firebasestorage.app',
    iosBundleId: 'cvproject.almomani.cvProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzRuV3LjiuFfFtDta4qYB-mJ5FEpywW9s',
    appId: '1:2460746938:web:e10d88f607bb3691352e83',
    messagingSenderId: '2460746938',
    projectId: 'cv-project290m',
    authDomain: 'cv-project290m.firebaseapp.com',
    storageBucket: 'cv-project290m.firebasestorage.app',
  );
}
